---
- name: Ensure ca-certificates is installed
  apt:
    name:
      - ca-certificates

- name: Import MySQL key
  apt_key:
    url: 'https://repo.mysql.com/RPM-GPG-KEY-mysql'

- name: Enable MySQL repo
  apt_repository:
    repo: >
      deb http://repo.mysql.com/apt/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }}
      mysql-{{ mysql_version }}

- name: Check if MySQL is already installed
  stat:
    path: /var/lib/mysql
  register: _installed

- name: Set root MySQL password
  debconf:
    name: mysql-community-server
    question: mysql-community-server/root-pass
    vtype: password
    value: '{{ mysql_root_password }}'
  when: _installed.stat.isdir is not defined

- name: Confirm root MySQL password
  debconf:
    name: mysql-community-server
    question: mysql-community-server/re-root-pass
    vtype: password
    value: '{{ mysql_root_password }}'
  when: _installed.stat.isdir is not defined

- name: Install MySQL packages
  apt:
    name: '{{ mysql_packages }}'

- name: Ensure MySQL is enabled and running
  service:
    name: mysql
    state: started
    enabled: True
